# Generated by Django 3.2.6 on 2021-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=6)),
                ('category', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=15)),
                ('question', models.CharField(max_length=550)),
                ('correct_answer', models.CharField(max_length=50)),
                ('incorrect_answer_one', models.CharField(max_length=50)),
                ('incorrect_answer_two', models.CharField(max_length=50)),
                ('incorrect_answer_three', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
